### ISSUE TITLE
Gather facts  stopped working after upgrading ansible version 2.4.0

### ISSUE THREAD

**Issue by Sush002** [rundeck-plugins/ansible-plugin#144]
I had a rundeck setup up and running. Recently I upgraded Ansible version to  2.4.0 , after that I am seeing NullPointer Exception while trying to gather facts with same resource model configurations.

When I turn off the gather facts  , the nodes get discovered without any info with them  ,

System details:
###########
CentOs 7 
Rundeck 2.8.4-1    ( rpm version ) 
Plugin : ansible-plugin-2.2.0.jar
ansible 2.4.0
#############

Below is log from service.log

PLAY RECAP *********************************************************************
host1            : ok=2    changed=1    unreachable=0    failed=0   
host2             : ok=2    changed=1    unreachable=0    failed=0   

ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 2.source (com.batix.rundeck.plugins.AnsibleResourceModelSourceFactory), project: test] 
java.lang.NullPointerException
	at com.batix.rundeck.plugins.AnsibleResourceModelSource.getNodes(AnsibleResourceModelSource.java:274)
	at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:113)
	at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:327)
	at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes$0.call(Unknown Source)
	at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:42)
	at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source)
	at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy:261)
	at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy)
	at sun.reflect.GeneratedMethodAccessor1716.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at com.codahale.metrics.Timer$time$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at com.codahale.metrics.Timer$time$0.call(Unknown Source)
	at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:190)
	at sun.reflect.GeneratedMethodAccessor327.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:59)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:230)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:96)
	at rundeck.services.NodeService.loadNodes(NodeService.groovy:273)
	at sun.reflect.GeneratedMethodAccessor1657.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:80)
	at rundeck.services.NodeService.this$dist$invoke$1(NodeService.groovy)
	at rundeck.services.NodeService$3.methodMissing(NodeService.groovy)
	at sun.reflect.GeneratedMethodAccessor1421.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:933)
	at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1256)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1209)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:807)
	at rundeck.services.NodeService$3.invokeMethod(NodeService.groovy)
	at groovy.lang.MetaClassImpl.invokeMethodOnGroovyObject(MetaClassImpl.java:1272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1166)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at rundeck.services.NodeService$_3_reload_closure1.doCall(NodeService.groovy:125)
	at rundeck.services.NodeService$_3_reload_closure1.doCall(NodeService.groovy)
	at sun.reflect.GeneratedMethodAccessor1742.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:251)
	at java.lang.Thread.run(Thread.java:748)
************************************************************************************

Project Setup Details:
###################
project.ansible-inventory=/opt/ansible/miscservers/inventories/hosts
project.description=
project.disable.executions=false
project.disable.schedule=false
project.jobs.gui.groupExpandLevel=1
project.name=test
project.nodeCache.delay=30
project.nodeCache.enabled=false
project.ssh-authentication=privateKey
project.ssh-command-timeout=0
project.ssh-connect-timeout=0
project.ssh-keypath=/opt/rundeck/.ssh/id_rsa
resources.source.1.config.file=/opt/rundeck/projects/test/etc/resources.xml
resources.source.1.config.format=resourcexml
resources.source.1.config.generateFileAutomatically=true
resources.source.1.config.includeServerNode=true
resources.source.1.config.requireFileExists=false
resources.source.1.type=file
resources.source.2.config.ansible-become=false
resources.source.2.config.ansible-gather-facts=true
resources.source.2.config.ansible-ignore-errors=true
resources.source.2.config.ansible-inventory=/opt/ansible/miscservers/inventories/hosts
resources.source.2.config.ansible-ssh-auth-type=privateKey
resources.source.2.config.ansible-ssh-keypath=/opt/rundeck/var/storage/content/keys/ansible/ansible_control_node_key
resources.source.2.config.ansible-ssh-user=ansible
resources.source.2.type=com.batix.rundeck.plugins.AnsibleResourceModelSourceFactory
service.FileCopier.default.provider=jsch-scp
service.NodeExecutor.default.provider=jsch-ssh

**Comment by DerekTBrown** [comment]
ansible-rundeck-plugin should create a folder within `/tmp` with a playbook as well as data from the fact gathering run (you should see it if debugging is enabled).  Could you locate the directory from this run, and report the contents of the `/data` file?

**Comment by Sush002** [comment]
with debug log on I see below output in the logs 

############################
changed: [ftldwsdns01 -> localhost] => {
    "changed": true, 
    "checksum": "016bb115add92b531877b4b2cbe4df2be5bcace8", 
    "dest": "/tmp/rundeck/ansible-hosts1050414491917586140/data/ftldwsdns01", 
    "failed": false, 
    "gid": 5518, 
    "group": "rundeck", 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": false, 
            "content": null, 
            "delimiter": null, 
            "dest": "/tmp/rundeck/ansible-hosts1050414491917586140/data/ftldwsdns01", 
            "directory_mode": null, 
            "follow": true, 
            "force": true, 
            "group": null, 
            "local_follow": null, 
            "mode": null, 
            "original_basename": "host-tpl.j2", 
            "owner": null, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/opt/rundeck/.ansible/tmp/ansible-tmp-1504371718.35-160418239331687/source", 
            "unsafe_writes": null, 
            "validate": null
        }
    }, 
    "md5sum": "7fbb38bcebb1341479dbb17c9cad2e71", 
    "mode": "0664", 
    "owner": "rundeck", 
    "size": 26242, 
    "src": "/opt/rundeck/.ansible/tmp/ansible-tmp-1504371718.35-160418239331687/source", 
    "state": "file", 
    "uid": 1001

#############################

The portion under ### repeats for each host .  
so under the data folder I see  files named after the hostname mentioned in the inventory and the files contain details about host in json format. These are probably facts gathered by the  playbook.

for eg: 
[root@ftlpwstools06 13:06 logs]# cd /tmp/rundeck/ansible-hosts1050414491917586140/data
[root@ftlpwstools06 13:06 data]# ll
total 632
-rw-rw-r-- 1 rundeck rundeck  45851 Sep  2 13:01 ftldwsdns01
-rw-rw-r-- 1 rundeck rundeck 254216 Sep  2 13:01 ftlpwskcint02
-rw-rw-r-- 1 rundeck rundeck 257074 Sep  2 13:01 ftlpwsyum02



Out of curiosity , the file created under the "/opt/rundeck/.ansible/tmp/ansible-tmp-1504371718.35-160418239331687/source" gets deleted just before the above mentioned ansible debug logs gets printed . Is it the source ,code is looking for ?
the log corresponding to this looks like:
<localhost> EXEC /bin/sh -c 'rm -f -r /opt/rundeck/.ansible/tmp/ansible-tmp-1504371718.35-160418239331687/ > /dev/null 2>&1 && sleep 0'


Thank you for the response!!

**Comment by DerekTBrown** [comment]
The error that you are seeing has to do with writing the output to JSON.  I will have to take a look at 2.4.0 myself.

**Comment by Sush002** [comment]
Thank you !! In case it can help , I am attaching the example of file which it creates in data folder in tmpdir.
[host_Fact.zip](https://github.com/Batix/rundeck-ansible-plugin/files/1273655/host_Fact.zip)

**Comment by brokenjacobs** [comment]
I'm having an issue on 2.3.2 where inventory discovery hangs and I get a backlog of MANY ansible workers until max processes are built up. Trying to see if its related to this issue.

**Comment by davistran86** [comment]
I'm also having this issue on Ansible 2.4.0 Rundeck 2.9.3.
If only one host then it's ok, but if I add another host then it's failed

> PLAY [all] *********************************************************************
> 
> TASK [Gathering Facts] *********************************************************
> ok: [192.168.1.6]
> ok: [192.168.1.7]
> 
> TASK [file] ********************************************************************
> changed: [192.168.1.7 -> localhost]
> 
> TASK [template] ****************************************************************
> changed: [192.168.1.6 -> localhost]
> changed: [192.168.1.7 -> localhost]
> 
> PLAY RECAP *********************************************************************
> 192.168.1.6                : ok=2    changed=1    unreachable=0    failed=0
> 192.168.1.7                : ok=3    changed=2    unreachable=0    failed=0
> 
> ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 1.source (com.batix.rundeck.plugins.AnsibleResourceModelSourceFactory), project: Windows]
> java.lang.NullPointerException
>         at com.batix.rundeck.plugins.AnsibleResourceModelSource.getNodes(AnsibleResourceModelSource.java:274)
>         at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
>         at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:113)
>         at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:327)
>         at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
>         at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source)
>         at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:42)
>         at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source)
>         at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy:265)
>         at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
>         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
>         at groovy.lang.Closure.call(Closure.java:414)
>         at groovy.lang.Closure.call(Closure.java:408)
>         at com.codahale.metrics.Timer.time(Timer.java:99)
>         at com.codahale.metrics.Timer$time$0.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
>         at com.codahale.metrics.Timer$time$0.call(Unknown Source)
>         at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:190)
>         at sun.reflect.GeneratedMethodAccessor394.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
>         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
>         at groovy.lang.Closure.call(Closure.java:414)
>         at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:62)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:233)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:101)
>         at rundeck.services.NodeService.loadNodes(NodeService.groovy:277)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
>         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
>         at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:82)
>         at rundeck.services.NodeService.this$dist$invoke$1(NodeService.groovy)
>         at rundeck.services.NodeService$3.methodMissing(NodeService.groovy)
>         at sun.reflect.GeneratedMethodAccessor760.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:944)
>         at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1267)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1220)
>         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:815)
>         at rundeck.services.NodeService$3.invokeMethod(NodeService.groovy)
>         at groovy.lang.MetaClassImpl.invokeMethodOnGroovyObject(MetaClassImpl.java:1283)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1177)
>         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
>         at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
>         at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy:129)
>         at rundeck.services.NodeService$3$_reload_closure1.doCall(NodeService.groovy)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
>         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1218)
>         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
>         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
>         at groovy.lang.Closure.call(Closure.java:414)
>         at groovy.lang.Closure.call(Closure.java:408)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:251)
>         at java.lang.Thread.run(Thread.java:748)
> WARN  LoggingResourceModelSourceCache: [ResourceModelSource: 1.source (com.batix.rundeck.plugins.AnsibleResourceModelSourceFactory), project: Windows] Returning cached model data

**Comment by mrala** [comment]
@DerekTBrown, did the structure of the JSON object change?

**Comment by mrala** [comment]
Same issue with Ansible 2.5.0, the current devel branch.

**Comment by bessie555** [comment]
I solved the problem temporarily by downgrading to Ansible 2.3.1, then all started working fine again.

For those interested how to downgrade Ansible, here are the steps I followed:

1) sudo apt-get remove ansible
2) sudo apt purge ansible
3) wget https://launchpad.net/~ansible/+archive/ubuntu/ansible/+files/ansible_2.3.1.0-1ppa~yakkety_all.deb
4) sudo dpkg -i ansible_2.3.1.0-1ppa-yakkety_all.deb

**Comment by dxc-martin-aksel-jensen** [comment]
Try out the newly released 2.2.2, it should fix the issue

**Comment by mrala** [comment]
@dxc-martin-aksel-jensen, I can confirm that 2.2.2 does resolve the issue with Ansible stable-2.4.

**Comment by hargut** [comment]
Updating to 2.2.2 fixed the issue for us as well.

**Comment by apollotonkosmo** [comment]
Upgrading the plugin to 2.2.2 fixed the problem for me as well! Thank everyone!

**Comment by apollotonkosmo** [comment]
Is it possible to define an ansible.cfg for every project or for every job?
Thanks
