### ISSUE TITLE
Ansible Node facts gathering issue

### ISSUE THREAD

**Issue by alexmaccabi** [rundeck-plugins/ansible-plugin#155]
[172.31.25.191.txt](https://github.com/Batix/rundeck-ansible-plugin/files/1425074/172.31.25.191.txt)
Hi, 
I`m facing some issue getting facts from ansible hosts. 
Ansible Plugin 2.2.1
Rundeck 2.10.0-1

Ansible resource module configuration:

ansible inventory File path: /etc/ansible/inventory/ec2.py Ansible config file path: /etc/ansible/ansible.cfg Gather Facts: Yes Disable Limit: Yes SSH User: ec2-user

Browning to nodes, the filtered node is shown but not all facts are collected:

![rundeck-ansible-tags](https://user-images.githubusercontent.com/3840250/32143915-c7b6f87e-bcb9-11e7-8f44-f54fcd1bbffa.PNG)

Checking the facts file in data:
/tmp/rundeck/ansible-hosts9029910315949001697/data/172.31.25.191
File attached. 

I've saw some errors in: Service.log 

TASK [file] ********************************************************************
changed: [172.31.25.191 -> localhost]

TASK [template] ****************************************************************
changed: [172.31.25.191 -> localhost]

PLAY RECAP *********************************************************************
172.31.25.191              : ok=3    changed=2    unreachable=0    failed=0

ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 1.source (com.batix.rundeck.plugins.AnsibleResourceModelSourceFactory), project: Ansible-Play]
java.lang.NullPointerException
        at com.batix.rundeck.plugins.AnsibleResourceModelSource.getNodes(AnsibleResourceModelSource.java:287)
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport$LoadedSource.getNodes(ProjectNodeSupport.java:418)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:118)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:327)
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
        at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source)
        at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:42)
        at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source)
        at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy:265)

Much help appreciated
thanks

**Comment by dxc-martin-aksel-jensen** [comment]
Are you using Centos or non-Debian distribution?

**Comment by alexmaccabi** [comment]
its CentOS flavor: amzn-ami-hvm-2017.09.0.20170930-x86_64-gp2

**Comment by dxc-martin-aksel-jensen** [comment]
Same problem here, it looks like it's because the ansible gathered fact about `lsb_release` is an empty object and the plugin assumes if it exists there's an `description` property as well.

Got:
```json
"lsb_release": { }
```

Expected:
```json
"lsb_release": { "description": "..." }
```

**Comment by alexmaccabi** [comment]
Alright so I've got it working by installing:

                   yum install redhat-lsb-core

![facts](https://user-images.githubusercontent.com/3840250/32324561-7cb12eb2-bfd4-11e7-8f15-0ef4f7e3523f.PNG)
