### ISSUE TITLE
Failed to connect to the host via ssh: Host key verification failed

### ISSUE THREAD

**Issue by deleutre** [rundeck-plugins/ansible-plugin#204]
Hello all,

I try rundeck with ansible ping job module on one node name "centos"
I got both, ssh connexion error, and writing permission to /etc/ansible 

Could you please help me ?
Thanks 

**PROJET CONFIG** 
_#edit below
project.ansible-executable=/bin/sh
project.disable.executions=false
project.disable.schedule=false
project.jobs.gui.groupExpandLevel=1
project.name=Ansible
project.nodeCache.delay=30
project.nodeCache.enabled=true
project.ssh-authentication=privateKey
project.ssh-keypath=/var/lib/rundeck/.ssh/id_rsa
resources.source.1.config.file=/var/rundeck/projects/Ansible/etc/resources.xml
resources.source.1.config.generateFileAutomatically=true
resources.source.1.config.includeServerNode=true
resources.source.1.config.requireFileExists=false
resources.source.1.config.writeable=false
resources.source.1.type=file
service.FileCopier.default.provider=com.batix.rundeck.plugins.AnsibleFileCopier
service.NodeExecutor.default.provider=com.batix.rundeck.plugins.AnsibleNodeExecutor_

**FILE /etc/ansible/hosts**
centos ansible_user=root ansible_ssh_private_key_file=/root/.ssh/id_rsa

**ERROR MESSAGE**
_[workflow] Begin execution: node-first
Start EngineWorkflowExecutor
Building initial state and rules...
Update conditional state: {before.step.1=true, after.step.1=false}
start conditions for step [1]: []
Create rule engine with rules: RuleEngine{ruleSet=[Rule: Conditions([(step.any.flowcontrol.halt == 'true')]) => DataState{state={workflow.done=true}}, Rule: Conditions([(step.any.state.failed == 'true'), (workflow.keepgoing == 'false')]) => DataState{state={workflow.done=true}}, Rule: Conditions([]) => DataState{state={step.1.start=true}}]}
Create workflow engine with state: StateLogger{state=DataState{state={job.successOnEmptyNodeFilter=false, job.executionType=user, job.url=http://deploybox.lirmm.fr:4440/project/Ansible/execution/follow/51, job.filter=centos, job.id=dec622b6-37c7-409f-ac15-a65ae847f8a2, job.loglevel=DEBUG, job.wasRetry=false, job.project=Ansible, before.step.1=true, after.step.1=false, job.retryInitialExecId=0, job.username=admin, job.retryAttempt=0, job.user.name=admin, workflow.keepgoing=false, job.execid=51, job.serverUrl=http://deploybox.lirmm.fr:4440/, job.name=ping, job.threadcount=1}}}
Begin: Workflow begin
WillProcessStateChange: saw state changes: {workflow.state=started}
Update conditional state: {workflow.state=started}
Update conditional state: {step.1.start=true}
DidProcessStateChange: applied state changes and rules (changed? true): StateLogger{state=DataState{state={job.successOnEmptyNodeFilter=false, job.executionType=user, job.url=http://deploybox.lirmm.fr:4440/project/Ansible/execution/follow/51, job.filter=centos, job.id=dec622b6-37c7-409f-ac15-a65ae847f8a2, job.loglevel=DEBUG, job.wasRetry=false, job.project=Ansible, before.step.1=true, step.1.start=true, after.step.1=false, workflow.state=started, job.retryInitialExecId=0, job.username=admin, job.retryAttempt=0, job.user.name=admin, workflow.keepgoing=false, job.execid=51, job.serverUrl=http://deploybox.lirmm.fr:4440/, job.name=ping, job.threadcount=1}}}
WillRunOperation: operation starting: Step{stepNum=1, label='null'}
LoopProgress: Pending(1) => run(1), skip(0), remain(0)
[workflow] Begin step: 1,com.batix.rundeck.plugins.AnsibleModuleWorkflowStep
1: Workflow step executing: StepExecutionItem{type='com.batix.rundeck.plugins.AnsibleModuleWorkflowStep', keepgoingOnSuccess=false, hasFailureHandler=false}
 procArgs: [ansible, all, -m, ping, -t, /etc/ansible, -l, centos, -vvv]
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/rundeck/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin
META: ran handlers
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/ping.py
<centos.net.lirmm> ESTABLISH SSH CONNECTION FOR USER: root
<centos.net.lirmm> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/var/lib/rundeck/.ansible/cp/91459fd2e1 centos.net.lirmm '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<centos.net.lirmm> (255, '', 'Host key verification failed.\r\n')
centos.net.lirmm | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Host key verification failed.\r\n", 
    "unreachable": true
}
 [WARNING]: Unable to write to centos.net.lirmm's file: [Errno 13] Permission
denied: u'/etc/ansible/centos.net.lirmm'
ERROR: Ansible execution returned with non zero code.
Failed executing step plugin [com.batix.rundeck.plugins.AnsibleModuleWorkflowStep]: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: ERROR: Ansible execution returned with non zero code.
	at com.batix.rundeck.plugins.AnsibleModuleWorkflowStep.executeStep(AnsibleModuleWorkflowStep.java:83)
	at com.dtolabs.rundeck.core.execution.workflow.steps.StepPluginAdapter.executeWorkflowStep(StepPluginAdapter.java:114)
	at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:103)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWFItem(BaseWorkflowExecutor.java:291)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflowStep(BaseWorkflowExecutor.java:687)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepCallable.apply(StepCallable.java:71)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:73)
	at com.dtolabs.rundeck.core.execution.workflow.engine.StepOperation.apply(StepOperation.java:31)
	at com.dtolabs.rundeck.core.rules.WorkflowEngineOperationsProcessor.lambda$processRunnableOperations$31(WorkflowEngineOperationsProcessor.java:222)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.batix.rundeck.core.AnsibleException: ERROR: Ansible execution returned with non zero code.
	at com.batix.rundeck.core.AnsibleRunner.run(AnsibleRunner.java:508)
	at com.batix.rundeck.plugins.AnsibleModuleWorkflowStep.executeStep(AnsibleModuleWorkflowStep.java:81)
	... 14 more

1: Workflow step finished, result: AnsibleNonZero: ERROR: Ansible execution returned with non zero code.
[workflow] Finish step: 1,com.batix.rundeck.plugins.AnsibleModuleWorkflowStep
OperationSuccess: operation succeeded: StepSuccess{stepNum=1, stepResultCapture=StepResultCapture{stepResult=AnsibleNonZero: ERROR: Ansible execution returned with non zero code., stepSuccess=false, statusString='null', controlBehavior=AnsibleNonZero: ERROR: Ansible execution returned with non zero code., resultData=MultiDataContextImpl(map={}, base=null)}, newState=DataState{state={step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.state=failure, after.step.1=true}}}
WillProcessStateChange: saw state changes: {before.step.1=false, step.1.state=failure, after.step.1=true, step.1.completed=true, step.any.state.failed=true}
Update conditional state: {before.step.1=false, step.1.state=failure, after.step.1=true, step.1.completed=true, step.any.state.failed=true}
Update conditional state: {workflow.done=true, step.1.start=true}
DidProcessStateChange: applied state changes and rules (changed? true): StateLogger{state=DataState{state={job.url=http://deploybox.lirmm.fr:4440/project/Ansible/execution/follow/51, workflow.done=true, job.id=dec622b6-37c7-409f-ac15-a65ae847f8a2, step.any.state.failed=true, job.loglevel=DEBUG, after.step.1=true, workflow.state=started, job.retryInitialExecId=0, job.user.name=admin, job.name=ping, step.1.state=failure, job.successOnEmptyNodeFilter=false, job.executionType=user, job.filter=centos, step.1.completed=true, job.wasRetry=false, job.project=Ansible, before.step.1=false, step.1.start=true, job.username=admin, job.retryAttempt=0, workflow.keepgoing=false, job.execid=51, job.serverUrl=http://deploybox.lirmm.fr:4440/, job.threadcount=1}}}
WorkflowEndState: Workflow end state reached.
WillShutdown: Workflow engine shutting down
Complete: Workflow complete: [Step{stepNum=1, label='null'}: StepSuccess{stepNum=1, stepResultCapture=StepResultCapture{stepResult=AnsibleNonZero: ERROR: Ansible execution returned with non zero code., stepSuccess=false, statusString='null', controlBehavior=AnsibleNonZero: ERROR: Ansible execution returned with non zero code., resultData=MultiDataContextImpl(map={}, base=null)}, newState=DataState{state={step.1.completed=true, step.any.state.failed=true, before.step.1=false, step.1.state=failure, after.step.1=true}}}]
[workflow] Finish execution:  node-first: [Workflow result: , step failures: {1=AnsibleNonZero: ERROR: Ansible execution returned with non zero code.}, status: failed]
[Workflow result: , step failures: {1=AnsibleNonZero: ERROR: Ansible execution returned with non zero code.}, status: failed]
Execution failed: 51 in project Ansible: [Workflow result: , step failures: {1=AnsibleNonZero: ERROR: Ansible execution returned with non zero code.}, status: failed]_

**Comment by fdevans** [comment]
Sorry we missed this. If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
