### ISSUE TITLE
Can't load hosts from inventory

### ISSUE THREAD

**Issue by GiovanniPaoloGibilisco** [rundeck-plugins/ansible-plugin#22]
Hi, 
I'm runnng v1.2.2 and ansible 2.0.2.0 on ubuntu 14.04. I-m able to create a new project with the settings specified in the readme but under Nodes i only see the local host

![image](https://cloud.githubusercontent.com/assets/5967863/14859147/28d02b30-0ca3-11e6-9857-a548ce61bce3.png)

I'm able to run without any problem
`su rundeck -s /bin/bash -c "ansible all -m ping"`

the file permission for `/etc/ansible/hosts` and `/etc/ansible/ansible.cfg` are:

`-rw-rw-rw-   1 root root 10462 Apr 27 15:34 ansible.cfg
-rw-rw-rw-   1 root root   231 Apr 27 16:11 hosts`

ansible hosts file contains a few entries like:

[fixed]
movvml120
movvml121
movvml122
movvml123

[floating]
movvml124

Service log reports the following error:

```
ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 2.com.batix.rundeck.AnsibleResourceModelSourceFactory (Ansible Resource Model Source), project: Ansible]
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Error reading facts.
        at com.batix.rundeck.AnsibleResourceModelSource.getNodes(AnsibleResourceModelSource.java:227)
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:91)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:266)
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
        at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:26)
        at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy:232)
        at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at com.codahale.metrics.Timer$time$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at com.codahale.metrics.Timer$time$0.call(Unknown Source)
        at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:174)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:59)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:230)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:96)
        at rundeck.services.NodeService$_loadNodes_closure4.doCall(NodeService.groovy:239)
        at rundeck.services.NodeService$_loadNodes_closure4.doCall(NodeService.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at groovy.lang.Closure.run(Closure.java:504)
        at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:251)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.NoSuchFileException: /tmp/rundeck/ansible-hosts8704990301932554303/data
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:426)
        at java.nio.file.Files.newDirectoryStream(Files.java:413)
        at com.batix.rundeck.AnsibleResourceModelSource.getNodes(AnsibleResourceModelSource.java:73)
        ... 65 more
```

The folder /tmp/rundeck/ansible-hosts8704990301932554303/ contains the following entries:

```
-rw-rw-r--  1 rundeck rundeck   50 Apr 27 17:54 gather-hosts.retry
-rw-rw-r--  1 rundeck rundeck  238 Apr 27 17:54 gather-hosts.yml
drwx------  3 rundeck rundeck 4096 Apr 27 17:54 $HOME/
-rw-rw-r--  1 rundeck rundeck   53 Apr 27 17:54 host-tpl.j2
```

a folder named `$HOME` looks strange to me..

**Comment by manchot0** [comment]
Hi,

Same here with v 1.2.2, rundeck 2.6.6-1 and ansible 2.0.2.0 on ubuntu 14.04.4.
I have the same error in log with also the $HOME in /tmp

**Comment by suivethefirst** [comment]
I have the same problem, same error, but not $HOME in /tmp/...

**Comment by frozenice** [comment]
Can you give the new [v1.2.3](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/1.2.3) a shot?

**Comment by suivethefirst** [comment]
No joy for me with v1.2.3 - still getting errors like:
`Caused by: java.nio.file.NoSuchFileException: /tmp/rundeck/ansible-hosts3290294940282592857/data`
in service.log. And there is indeed no directory or file named data in that directory.

**Comment by suivethefirst** [comment]
Disregard that last comment. I created a new project and can now successfully load Ansible hosts from the default Ansible inventory. Excellent work @frozenice and many thanks for this fix.

**Comment by GiovanniPaoloGibilisco** [comment]
Version 1.2.3 seem to have fixed the issue. 
Thanks!
