### ISSUE TITLE
cannot set attribute on fact gathering

### ISSUE THREAD

**Issue by Vebryn** [rundeck-plugins/ansible-plugin#293]
Hello,

Awesome plugin, congrats!

Facts are not displayed into Nodes view. A Java exception occurs after fact gathering.

```
PLAY RECAP *********************************************************************
sv1                        : ok=1    changed=1    unreachable=0    failed=0
sv2                        : ok=1    changed=1    unreachable=0    failed=0
sv3                        : ok=2    changed=2    unreachable=0    failed=0

java.lang.reflect.InvocationTargetException: Cannot set attribute
        at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1020)
        at org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:823)
        at org.apache.commons.beanutils.BeanUtils.populate(BeanUtils.java:431)
        at com.dtolabs.rundeck.core.common.NodeEntryFactory.createFromMap(NodeEntryFactory.java:95)
        at com.dtolabs.rundeck.core.common.NodesYamlParser.parse(NodesYamlParser.java:114)
        at com.dtolabs.rundeck.core.resources.format.ResourceYamlFormatParser.parseDocument(ResourceYamlFormatParser.java:88)
```

Ansible succeed in creating host-tpl.j2 files into /var/lib/rundeck/.ansible/tmp/. Exception appear after gathering playbook.

Any idea ?

Best regards.

**Comment by fdevans** [comment]
Sorry we missed this. If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
