### ISSUE TITLE
Additional host tag setting ignored when Gather Facts = No

### ISSUE THREAD

**Issue by jimr6007** [rundeck-plugins/ansible-plugin#401]
RD version 5.7/latest
Ansible plugin 4.0.5

As we know, "Gather Facts = No" means generate nodes via ansible-inventory command instead of running the gather-hosts playbook.

With Gather Facts = Yes, the "Additional host tag" is applied as expected.

With Gather Facts = No, the "Additional host tag" value if provided is not applied to the generated Rundeck nodes.

**Comment by plaqdk** [comment]
RD version 5.8/latest
Ansible plugin 4.0.6-SNAPSHOT  (ansible-plugin-4.0.5.jar)

If i run with Gather Facts on I get host and facts

If I set it to false I get this error 

        at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:284) ~[spring-core-5.3.34.jar!/:5.3.34]                                                                                        
        at java.lang.Thread.run(Thread.java:829) ~[?:?]                                                                                                                                                                                                        
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key                                            
 in 'string', line 2, column 1:                                                                                                
    -vvvv to see details                                                                                                       
    ^                                                                                                                                                                                                                                                          
could not find expected ':'                                                                                                                                                                                                                                    
 in 'string', line 3, column 1:                                                                                                                                                                                                                                
    all:                                                                                                                       
    ^

**Comment by MegaDrive68k** [comment]
Hi folks, could you try the ansible plugin[ v4.0.7](https://github.com/rundeck-plugins/ansible-plugin/releases/tag/v4.0.7)? By default Rundeck 5.8.0 includes v4.0.5. Take a look at this: https://docs.rundeck.com/docs/administration/configuration/plugins/installing.html

**Comment by plaqdk** [comment]
Just made a new issue to not take focus from this issue as this is regarding tags an my problem is related to host vars 

moved to #406

**Comment by fdevans** [comment]
Sorry we missed this. If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
