### ISSUE TITLE
No nodes are displayed if any are unreachable

### ISSUE THREAD

**Issue by chelming** [rundeck-plugins/ansible-plugin#53]
If any of my hosts are unreachable the plugin seems to dislike the non-zero exit code returned by Ansible and won't show _any_ hosts in the nodes section. If I change my hosts file so only the online hosts are in inventory, it works as expected.

```
PLAY RECAP *********************************************************************
SERVER-01 : ok=3    changed=2    unreachable=0    failed=0
SERVER-02 : ok=2    changed=1    unreachable=0    failed=0
SERVER-03 : ok=0    changed=0    unreachable=1    failed=0
SERVER-04 : ok=0    changed=0    unreachable=1    failed=0
SERVER-05 : ok=0    changed=0    unreachable=1    failed=0
SERVER-06 : ok=2    changed=1    unreachable=0    failed=0
SERVER-07 : ok=0    changed=0    unreachable=1    failed=0
SERVER-08 : ok=2    changed=1    unreachable=0    failed=0
SERVER-09 : ok=2    changed=1    unreachable=0    failed=0
SERVER-10 : ok=0    changed=0    unreachable=1    failed=0
SERVER-11 : ok=0    changed=0    unreachable=1    failed=0
SERVER-12 : ok=0    changed=0    unreachable=1    failed=0
SERVER-13 : ok=0    changed=0    unreachable=1    failed=0
SERVER-14 : ok=0    changed=0    unreachable=1    failed=0
SERVER-15 : ok=0    changed=0    unreachable=1    failed=0
SERVER-16 : ok=0    changed=0    unreachable=1    failed=0
SERVER-17 : ok=2    changed=1    unreachable=0    failed=0
SERVER-18 : ok=2    changed=1    unreachable=0    failed=0
SERVER-19 : ok=2    changed=1    unreachable=0    failed=0
SERVER-20 : ok=2    changed=1    unreachable=0    failed=0
SERVER-21 : ok=2    changed=1    unreachable=0    failed=0
SERVER-22 : ok=0    changed=0    unreachable=1    failed=0
SERVER-23 : ok=0    changed=0    unreachable=1    failed=0
SERVER-24 : ok=0    changed=0    unreachable=1    failed=0
SERVER-25 : ok=2    changed=1    unreachable=0    failed=0
SERVER-26 : ok=0    changed=0    unreachable=1    failed=0
DATABASE-19 : ok=0    changed=0    unreachable=1    failed=0
DATABASE-20 : ok=0    changed=0    unreachable=1    failed=0
DATABASE-21 : ok=0    changed=0    unreachable=1    failed=0
DATABASE-22 : ok=0    changed=0    unreachable=1    failed=0
DATABASE-23 : ok=0    changed=0    unreachable=1    failed=0
DATABASE-24 : ok=0    changed=0    unreachable=1    failed=0
DATABASE-25 : ok=0    changed=0    unreachable=1    failed=0

ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 2.source (Ansible Resource Model Source), project: Ansible-test]
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Error running playbook.
        at com.batix.rundeck.AnsibleResourceModelSource.getNodes(AnsibleResourceModelSource.java:72)
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:92)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:292)
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
        at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source)
        at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:26)
        at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source)
        at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy:232)
        at rundeck.services.NodeService$_loadNodes_closure3.doCall(NodeService.groovy)
        at sun.reflect.GeneratedMethodAccessor820.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at com.codahale.metrics.Timer$time.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at com.codahale.metrics.Timer$time.call(Unknown Source)
        at MetricswebGrailsPlugin$_addDynamicMetricMethods_closure26.doCall(MetricswebGrailsPlugin.groovy:174)
        at sun.reflect.GeneratedMethodAccessor516.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at org.codehaus.groovy.runtime.metaclass.ClosureStaticMetaMethod.invoke(ClosureStaticMetaMethod.java:59)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:230)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:96)
        at rundeck.services.NodeService.loadNodes(NodeService.groovy:244)
        at sun.reflect.GeneratedMethodAccessor813.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:80)
        at rundeck.services.NodeService.this$dist$invoke$1(NodeService.groovy)
        at rundeck.services.NodeService$2.methodMissing(NodeService.groovy)
        at sun.reflect.GeneratedMethodAccessor741.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:933)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1256)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1209)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:807)
        at rundeck.services.NodeService$2.invokeMethod(NodeService.groovy)
        at groovy.lang.MetaClassImpl.invokeMethodOnGroovyObject(MetaClassImpl.java:1272)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1166)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
        at rundeck.services.NodeService$_2_reload_closure1.doCall(NodeService.groovy:96)
        at rundeck.services.NodeService$_2_reload_closure1.doCall(NodeService.groovy)
        at sun.reflect.GeneratedMethodAccessor946.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:251)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.batix.rundeck.AnsibleStepException: ERROR: Ansible execution returned with non zero code.
        at com.batix.rundeck.AnsibleRunner.run(AnsibleRunner.java:298)
        at com.batix.rundeck.AnsibleResourceModelSource.getNodes(AnsibleResourceModelSource.java:70)
        ... 82 more
WARN  LoggingResourceModelSourceCache: [ResourceModelSource: 2.source (Ansible Resource Model Source), project: Ansible-test] Returning cached model data
```

and with the edited inventory:

```
PLAY RECAP *********************************************************************
SERVER-01 : ok=3    changed=2    unreachable=0    failed=0
SERVER-02 : ok=2    changed=1    unreachable=0    failed=0
SERVER-06 : ok=2    changed=1    unreachable=0    failed=0
SERVER-08 : ok=2    changed=1    unreachable=0    failed=0
SERVER-09 : ok=2    changed=1    unreachable=0    failed=0
SERVER-17 : ok=2    changed=1    unreachable=0    failed=0
SERVER-18 : ok=2    changed=1    unreachable=0    failed=0
SERVER-19 : ok=2    changed=1    unreachable=0    failed=0
SERVER-20 : ok=2    changed=1    unreachable=0    failed=0
SERVER-21 : ok=2    changed=1    unreachable=0    failed=0

INFO  ExecutionUtilService: Execution successful: 41466
```

**Comment by yassineazzouz** [comment]
Hi @cwhits ,

Thanks for reporting this, I agree it is probably better if the host facts gathering omits bad hosts and still display good ones. Although errors due to unreachable hosts should not go silently. So probably it will be best if this still works and report errors at the same time, not sure if this can be done thought. I will investigate a nice way of doing it.

**Comment by chelming** [comment]
Perhaps something with error handling within the playbook?

http://docs.ansible.com/ansible/playbooks_error_handling.html

Edit: Never mind. :( That won't handle unreachable hosts.

**Comment by chelming** [comment]
@yassineazzouz _Is it better_ if the host facts gathering omits the bad ones? Wouldn't we want all of our inventory to reside under nodes within Rundeck and then let Ansible return the unreachable host error when we try and execute a command against that host? Or, if we're gathering facts, add a fact/tag to that host saying it's offline?

It already appears that if a host is imported (while online), it won't be removed later if it goes offline because of the crash then the non-zero exit code is returned.

**Comment by rubal033** [comment]
This also causes problem in updating the Resource model in Rundeck. If you provision new instances and some of your hosts are stop then it won't update the new instance to Rundeck resource model.

**Comment by telefax** [comment]
This constant rebuilding of nodes list is really really annoying. It makes it impossible to use ansible plugins for rundeck if I have some jobs thats going on while I'm working with other runbooks, for instance when having servers rebooting. 

Perhaps it could be possible to disable this auto generation some how, and only enable import from /etc/ansible/hosts when we explicitly need to rebuild the node list or catch new facts?

**Comment by javierurien** [comment]
+1. It should be possible to add reachable hosts and delete(ignore) unreachable/failed ones.

Regards

**Comment by QUASARFREAK** [comment]
Confirmed, I'm having the exact same problem.

**Comment by yassineazzouz** [comment]
Thanks for reporting this, Coming in next release :)

**Comment by yassineazzouz** [comment]
Hi @QUASARFREAK @javierurien @cwhits @rubal033 @telefax ,

This is resolved in release 2.0.0, please refer to the readme file for the full list of new features.

Thanks,

**Comment by rubal033** [comment]
Hi

I have tried release 2.0.0 and its not working fine with "Gather Facts" enabled.

If i enable gather facts checkbox it takes forever to update the nodes and never display it. In service logs i can see all the processing is getting complete but nodes won't get updated and Rundeck keeps showing "Loading matched nodes..." message.

**Comment by yassineazzouz** [comment]
Hi @rubal033 ,

Please note that old configurations does not work on v2.0, so you need to create a new project after setting the new plugin jar. you maybe have some hosts unreachable, are you using "Ignore Host Discovery Errors" ?

Thanks,

**Comment by rubal033** [comment]
Yes i have created a new project after installing the new release and yes "Ignore Host Discovery Errors" is also checked. It works fine if i don't use "Gather Facts" . But if use it then it won't show the nodes and i have to delete the project and create new to get the nodes without "Gather Facts".

Also while saving the project settings with "Gather Facts" enabled it takes lot of time to save , sometimes even i got session out during that time. And after re-login if i try to open the project setting it takes lot of time to open it. In service logs i am not getting any logs related to this.

Thanks

**Comment by yassineazzouz** [comment]
Hi @rubal033 , which rundeck version are you using ? also can you post the exact ansible command that is being executed ?

**Comment by rubal033** [comment]
Hi @yassineazzouz 

I am using Rundeck 2.6.8-1 . I am not executing any command, just trying to get Nodes by using "Ansible Resource Model" and stuck there only when the "Gather facts" is checked.

Right now not even able to open the setting for the project i am trying to populate nodes with.
In service logs i got logs as:

PLAY [all] *********************************************************************

TASK [file] ********************************************************************
changed: [tag-population-001 -> localhost] => {"changed": true, "gid": 1007, "group": "rundeck", "mode": "0775", "owner": "rundeck", "path": "/tmp/rundeck/ansible-hosts8305448749762189786/data", "size": 4096, "state": "directory", "uid": 1007}

TASK [template] ****************************************************************
changed: [broadcast-consumer-preemptive-ig-qzat -> localhost] => {"changed": true, "checksum": "c5859cac8a8ffc492edbd5659047768ba7429e23", "dest": "/tmp/rundeck/ansible-hosts8305448749762189786/data/broadcast-consumer-preemptive-ig-qzat", "gid": 1007, "group": "rundeck", "md5sum": "01238ec0c68c19da1844d83f3ab834b6", "mode": "0664", "owner": "rundeck", "size": 58222, "src": "/home/rundeck/.ansible/tmp/ansible-tmp-1476190652.53-239703006392661/source", "state": "file", "uid": 1007}
changed: [tag-population-001 -> localhost] => {"changed": true, "checksum": "5a1c37e556feea42461009f5a85e04be5aa7a691", "dest": "/tmp/rundeck/ansible-hosts8305448749762189786/data/tag-population-001", "gid": 1007, "group": "rundeck", "md5sum": "1d18e3a70046b8f3b990ab69c0757901", "mode": "0664", "owner": "rundeck", "size": 57776, "src": "/home/rundeck/.ansible/tmp/ansible-tmp-1476190652.47-111114993632118/source", "state": "file", "uid": 1007}

I have attached 2 screenshots:
1. Setting i am using with "Ansible Resource Model".
2. The status of my Nodes since last 1 hr.

![screen shot 2016-10-11 at 9 51 34 pm](https://cloud.githubusercontent.com/assets/17160090/19279158/d5b243fa-8ffd-11e6-83bd-715d04548585.png)
![screen shot 2016-10-11 at 9 50 09 pm](https://cloud.githubusercontent.com/assets/17160090/19279157/d5a39e36-8ffd-11e6-89bb-e99bb9f11047.png)

**Comment by QUASARFREAK** [comment]
With the 2.0 version it worked here, thanks!

**Comment by yassineazzouz** [comment]
Hi @rubal033 

I don't think this is related to the plugin itself or rundeck I tested with the same rundeck version and it works perfectly fine for me. I think the ansible process is hanging, this could be related to multiple things : 
- ansible could be waiting for an authentication password
- Host checking enabled
- Hosts not responding

What I typically do is enable ansible logging in rundeck to look at what ansible is doing in the background, you can do so, by setting (uncommanting): 
log_path = /var/log/ansible.log
in /etc/ansible/ansible.cfg, make sure the file is writable by rundeck, you can juste put it to 0666 for testing.
then look at the logs in /var/log/ansible.log to see why the process is hanging. If you could try the command that is being executed and post the full output I can probably tell more what is going on.
A good idea will be also to check the running ansible processes, I have seen some cases in v1.x where rundeck leaves a lot of orphans processes, and that was fixed in v2.0 so I suggest you try : 
ps -eaf | grep -i ansible (then kill any running process)
Another good practice is to add : export ANSIBLE_HOST_KEY_CHECKING=False in your /etc/rundeck/profile to avoid problems related to host key checking.

I hope that helps,

**Comment by rubal033** [comment]
Hi

Getting my nodes populated with info. Looks like adding  export ANSIBLE_HOST_KEY_CHECKING=False in  /etc/rundeck/profile worked for me. 

It's not showing me all the nodes as while running playbook and i can see in logs those nodes showing they are unreachable and its look like ansible issue. 

Plugin is working fine for me. 

Thanks You

**Comment by yassineazzouz** [comment]
Thanks @rubal033 , glad it works for you, you can also try to register known hosts fingerprint, using "rundeck" user to avoid such issues, disabling host key checking is not safe. You need just to su - rundeck then do ssh to all hosts to make sure that all hosts fingerprint are registered. 
I usually automate this process in ansible, you can just include this script in your playbooks are just execute it whenever you add a new host:
- hosts: all
  gather_facts: False
  serial: 1
  tasks:
  - name: Make sure the known hosts file exists
    file: path={{ ssh_known_hosts_file }} state=file
    delegate_to: 127.0.0.1
    run_once: true
  - name: Scan the current public key of the server
    command: "ssh-keyscan -T 10 {{ inventory_hostname }}"
    changed_when: False
    register: current_host_key
    delegate_to: 127.0.0.1
  - name: Register the current public key
    lineinfile: >
      dest="{{ ssh_known_hosts_file }}"
      regexp="^(._){{ inventory_hostname }}(._)$"
      line="{{current_host_key.stdout}}"
    delegate_to: 127.0.0.1
    vars:
  - ssh_known_hosts_file: "~/.ssh/known_hosts"`

I hope that helps,

**Comment by rubal033** [comment]
Hi 

One more problem i am facing with using "gather facts" is that  Ansible skip some node to identify saying they are unreachable. But on running ping or setup on those nodes manually from Ansible always give me success and desired response. 

Is there any specific Ansible setting need to be done for the plugin ?

**Comment by yassineazzouz** [comment]
Hi @rubal033 ,

If your ansible commands are working fine with "rundeck" user the plugin should be working fine, it's just a wrapper. I suggest you enable file logging on your /etc/ansible/ansible.cfg ; just set : log_path = /var/log/ansible.log.
Then post the command being executed  for host discovery and the logs. then try to run the exact same command (with same options) just replace ansible-playbook with ansible all -m ping and keep all the other options and post the output.

Thanks,

**Comment by rubal033** [comment]
Hi @yassineazzouz 

i have enabled the  log_path = /var/log/ansible.log and got the attached output for the gathering hosts. I have then filtered unreachable host from that output and  ran the ping module for those filtered hosts and the output of that also attached with mail. All the running nodes responded with success to ping module.

Thanks

[playbook-output.txt](https://github.com/Batix/rundeck-ansible-plugin/files/539829/playbook-output.txt)
[ping_output.txt](https://github.com/Batix/rundeck-ansible-plugin/files/539830/ping_output.txt)

**Comment by rubal033** [comment]
Hi

This is resolved after making some changes to the ansible conf. related to ssh_arg. Also there is some problem with my dynamic inventory script gce.py replacing it with newer one helped in identifying the issue.

Thanks
