### ISSUE TITLE
Become password can't be passed to ansible process when SSH password is used for authentication

### ISSUE THREAD

**Issue by AlexZolotarenko** [rundeck-plugins/ansible-plugin#75]
Ansible version: 2.1, 2.2 
Rundeck version: 2.6.9
Ansible plugin: 2.0.1

I am using ansible workflowstep  in Rundeck with SSH password authentication and "become" with  password as well. 
For this I set "secure authentication" options for both ssh password and become password.
According to the logs, rundeck recognize that "--ask-pass" and "--ask-become-pass" should be passed to ansible.  
 But task execution fails with following exception:

```
Failed executing step plugin [com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep]: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: ERROR: Ansible IO failure.
        at com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep.executeStep(AnsiblePlaybookWorkflowStep.java:84)
        at com.dtolabs.rundeck.core.execution.workflow.steps.StepPluginAdapter.executeWorkflowStep(StepPluginAdapter.java:98)
        at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeStep(ExecutionServiceImpl.java:116)
        at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWFItem(BaseWorkflowStrategy.java:225)
        at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:303)
        at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflowItemsForNodeSet(BaseWorkflowStrategy.java:258)
        at com.dtolabs.rundeck.core.execution.workflow.StepFirstWorkflowStrategy.executeWorkflowImpl(StepFirstWorkflowStrategy.java:79)
        at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
        at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
Caused by: com.batix.rundeck.core.AnsibleException: ERROR: Ansible IO failure.
        at com.batix.rundeck.core.AnsibleRunner.run(AnsibleRunner.java:476)
        at com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep.executeStep(AnsiblePlaybookWorkflowStep.java:82)
        ... 8 more
Caused by: java.io.IOException: Stream Closed
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
        at com.batix.rundeck.core.AnsibleRunner.run(AnsibleRunner.java:450)
        ... 9 more
```

I am not sure if this is correct ( I am not a programmer at all ), but I have managed to fix this with following diff: 

```
--- a/src/main/java/com/batix/rundeck/core/AnsibleRunner.java
+++ b/src/main/java/com/batix/rundeck/core/AnsibleRunner.java
@@ -436,7 +437,11 @@ public class AnsibleRunner {
             OutputStream stdin = proc.getOutputStream();
             OutputStreamWriter out = new OutputStreamWriter(stdin);
             out.write(sshPass+"\n");
-            out.close();
+            if (become) {
+              out.flush();
+            } else {
+              out.close();
+            }
          } else {
             throw new AnsibleException("Missing ssh password.",AnsibleException.AnsibleFailureReason.AnsibleNonZero);
          }
```

**Comment by yassineazzouz** [comment]
Hi @AlexZolotarenko ,
Good catch ! thanks for reporting this. I will provide a fix for this ASAP.

**Comment by yassineazzouz** [comment]
Hi @AlexZolotarenko ,
This should be fixed in release 2.0.2
Thanks,

**Comment by stszap** [comment]
Don't know if my issue is related but I will post it here. I can't setup "Privilege escalation Password". I added new password via "Key Storage" page and then created a job with "Ansible Module" step with "Privilege Escalation" enabled. When I run this job I'm always prompted "SUDO password:" in console from which rundeck was started and job execution is blocked until password is entered. Am I doing something wrong? Tried this on rundeck 2.6.9 and 2.7.1, ansible-plugin 2.0.2 all from jar files. Without "Privilege escalation Password" and with "NOPASSWD" option in sudoers file everything works fine.
Thanks.

**Comment by DerekTBrown** [comment]
@stszap that doesn't seem like a rundeck configuration issue.  Logically your escalation user needs to have access to run on the system.  I am closing for now, but if this becomes an issue for others, we can add a warning to the GUI.

**Comment by ltamaster** [comment]
I am having a similar issue with the SSH password, it seems that the ansible plugin cannot pass the ssh password.

**Comment by thomasoliw** [comment]
Hello, 
I have the same problem as reported above on Rundeck 3.2.4 with ansible 2.9.2.
For my particular case, me and my fellow admins logon as ourselves and when we need sudo rights, we provide our password. 
The first step (logging in as ourselves) works fine using ssh-keys, however the second step where we need to give a password does not work, even though we have configured a "Privilege escalation Password Storage Path" that holds the needed password.

We always get the "BECOME password:" prompt in the terminal where Rundeck was started.
More details on the original post in "Google groups":
https://groups.google.com/forum/#!topic/rundeck-discuss/xta1AjlnOak

I am new to Rundeck, but it seems like the idea with the "Privilege escalation Password Storage Path" is to provide the needed secrets automatically? If so, it does not seem to work.

Kind Regards,

Thomas

**Comment by Iohannes-Nerevar** [comment]
Hi,
 
It seems I have the same problem. Subject mentioned here:
https://groups.google.com/g/rundeck-discuss/c/QwUFbjJG09c

Regards
